---
title: "Download and preprocess the Tabula Muris 10x data"
author: "Charlotte Soneson"
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 100)
```

## Download data

The count table was downloaded from [https://s3.amazonaws.com/czbiohub-tabula-muris/TM_droplet_mat.rds](https://s3.amazonaws.com/czbiohub-tabula-muris/TM_droplet_mat.rds), following instructions on [https://github.com/czbiohub/tabula-muris-vignettes/tree/master/data](https://github.com/czbiohub/tabula-muris-vignettes/tree/master/data) (accessed August 26, 2018).

The metadata was obtained from [https://github.com/czbiohub/tabula-muris-vignettes/tree/master/data](https://github.com/czbiohub/tabula-muris-vignettes/tree/master/data) (accessed August 26, 2018).

```{r}
suppressPackageStartupMessages({
    library(Matrix)
    library(SingleCellExperiment)
    library(readr)
    library(dplyr)
})

counts <- readRDS("TM_droplet_mat.rds")
metadata <- readr::read_csv("TM_droplet_metadata.csv")
```

## Generate `SingleCellExperiment` object

```{r}
stopifnot(all(colnames(counts) == metadata$cell))

droplet <- SingleCellExperiment(
    assay = list(counts = counts),
    colData = DataFrame(metadata %>% dplyr::rename(mouse_id = mouse.id,
                                                   mouse_sex = mouse.sex)),
    rowData = DataFrame(ID = rownames(counts),
                        Symbol = rownames(counts))
)
```

## Exclude ERCCs

```{r}
droplet <- droplet[grep("^ERCC-", rownames(droplet), invert = TRUE), ]
dim(droplet)
```

## Save `SingleCellExperiment` object

```{r}
droplet
head(colData(droplet))
saveRDS(droplet, file = "TabulaMurisDroplet.rds")
```

## Session info

```{r}
sessionInfo()
```
